linters:
    BorderZero:
        enabled: true

    CapitalizationInSelector:
        enabled: true

    ColorKeyword:
        enabled: true

    Comment:
        enabled: true

    DebugStatement:
        enabled: true

    DeclarationOrder:
        enabled: true

    DuplicateProperty:
        enabled: true

    EmptyLineBetweenBlocks:
        enabled: true
        ignore_single_line_blocks: true

    EmptyRule:
        enabled: true

    FinalNewline:
        enabled: true
        present: true

    HexLength:
        enabled: true
        style: short

    HexNotation:
        enabled: true
        style: lowercase

    HexValidation:
        enabled: true

    IdSelector:
        enabled: false

    IdWithExtraneousSelector:
        enabled: true

    Indentation:
        enabled: true
        width: 4

    LeadingZero:
        enabled: true
        style: include_zero

    MergeableSelector:
        enabled: true
        force_nesting: true

    NameFormat:
        enabled: true
        convention: hyphenated_lowercase

    # TODO: Get NestingDepth down to 3
    # Currently, it's disabled to not be noisy
    NestingDepth:
        enabled: false
        max_depth: 3

    PlaceholderInExtend:
        enabled: true

    PropertySortOrder:
        enabled: false

    PropertySpelling:
        enabled: true
        extra_properties:
            - '*zoom'

    # TODO: Get SelectorDepth down to 3
    # Currently, it's disabled to not be noisy
    SelectorDepth:
        enabled: false
        max_depth: 3

    Shorthand:
        enabled: true

    SingleLinePerSelector:
        enabled: true

    SpaceAfterComma:
        enabled: true

    SpaceAfterPropertyColon:
        enabled: true

    SpaceAfterPropertyName:
        enabled: true

    SpaceBeforeBrace:
        enabled: true
        allow_single_line_padding: false

    SpaceBetweenParens:
        enabled: true
        spaces: 0

    StringQuotes:
        enabled: true
        style: single_quotes

    TrailingSemicolonAfterPropertyValue:
        enabled: true

    QualifyingElement:
        enabled: true
        allow_element_with_attribute: true

    UnnecessaryMantissa:
        enabled: true

    UrlFormat:
        enabled: true

    UrlQuotes:
        enabled: true

    ZeroUnit:
        enabled: true

    Compass::*:
        enabled: false
